#pragma once
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include "imgui/imgui.h"
#include "imgui/imgui_impl_opengl3.h"
#include "imgui/imgui_impl_glfw.h"
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include "stb_image/stb_image.h"
#define GLM_ENABLE_EXPERIMENTAL
#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include <unordered_map>
#include <Windows.h>
#include <chrono>
#include <vector>
#include "ErrorLogging.h"
#include "Timer.h"